### ISSUE TITLE
Data accuracy improvements

### ISSUE THREAD

**Issue by quinndx** [stoogoff/sw-adversaries#1]
Hey! Great app! Just a few observations to improve data accuracy. :)

Data errors
* I don’t think the Skulduggery skill is appearing properly - it is missing on several profiles (such as Cautious Smuggler, Shipjacker, Slicer, Smuggler Baron, Street Tough etc.)
* Guilded Bounty Hunter - Expert Tracker talent reduces time by 50%, not 25% (this could either be a non-ranked variant of the PC 'Expert Tracker' talent or a typo in the source material - it doesn't indicate any skill ranks for the Guilded Bounty Hunter in either the AoR or F&D CRB).
* Imperial Stormtrooper Sergeant - incorrectly has the Overwhelming Fire talent.
* Imperial Army Officer - missing Ranged (Light) 2 and Warfare 2 skills.
* Imperial Gunnery Crew - missing Holdout Blaster from gear.
* Jedi-In-Hiding - missing Lightsaber 4 skill.
* Master Bounty Hunter - missing correct quantity of Stun Grenades (should be 4).
* Shadowport Mechanic - missing Underworld 2 skill.
* Shipjacker - incorrectly lists frag grenades in his gear (should be stun grenades).
* Slaver - missing Truncheon from gear.
* Tauntaun - incorrect soak and wound threshold (should be 5 and 15 respectively).
* Ugnaught mechanic - missing Stubborn and Dependable ability.

Typographical errors (not super important but makes searching titles from books easier)
* Assassin Droid's 'builtin-in' light blaster pistol - should be just built-in light blaster pistol.
* Rancor - missing ‘Captive’ in title.
* Destroyer Driod - missing ‘Droideka’ in title.
* Master Hunter - missing ‘Bounty’ in title.
* Wealthy Noble - vibrosword missing ‘antique’ in title.

Hope this helps!

Q

**Comment by stoogoff** [comment]
Thanks for the feedback. I'll go through these this evening and get them fixed. I can already see that skuldudggery is misspelt in the skill list.

**Comment by stoogoff** [comment]
These are now fixed, most of them were typos in the data.

One thing I did notice is the Guilded Bounty Hunter's Expert Tracker talent is slightly different between the AoR and FaD versions. The FaD version removes two setback dice from tracking while the AoR version only removes one. I've gone with the AoR version.
