### ISSUE TITLE
Loading Issue

### ISSUE THREAD

**Issue by dyre21** [stoogoff/sw-adversaries#14]
This is great work, I only have one problem. I get it to work fine on my laptop, but can't get it to work on my tablet, which is running windows. I'm using chrome, but I tried edge and it worked. Are you aware of any issue on Chrome?

**Comment by stoogoff** [comment]
I know it works in Chrome on Linux, OSX and Android so I'm surprised it doesn't work on Windows. Can you open the developer tools (F12) and copy the contents of the console for me please? That will help me in getting to the bottom of the problem.

**Comment by dyre21** [comment]
Thanks for the response, I tried something that I thought I had done already. Was just a cache issue, glad I figured it out because I hate taking my laptop to gaming.
    On Wednesday, February 14, 2018, 5:02:16 AM CST, Stoo <notifications@github.com> wrote:  
 
 
I know it works in Chrome on Linux, OSX and Android so I'm surprised it doesn't work on Windows. Can you open the developer tools (F12) and copy the contents of the console for me please? That will help me in getting to the bottom of the problem.
