### ISSUE TITLE
Vehicles

### ISSUE THREAD

**Issue by angrystatic** [stoogoff/sw-adversaries#16]
How about a parrallel site for vehicles? Data set would be smaller but it would certainly makes things easier for the busy GM. Something that can track all the different damage locations / shields would put this over the top.

And Thanks for the tool. Great work all you.

I also suggest some kind of donation button, if that's allowed. Bury it in the about popup?

**Comment by tmilktoast** [comment]
For vehicles and other things, there's this: http://swrpg.viluppo.net/transportation/

Hasn't been updated in a while, though, and isn't nearly as nice as this Adversaries site.

**Comment by stoogoff** [comment]
Good suggestion on the donate button, I've added that :)

For vehicles what I'm thinking of doing is making it so you can add a vehicle profile to an adversary profile. So you've got a squad of TIE Pilot minions and you want to put them all in TIE Interceptors, the app gives you a selection of vehicles, you find the one you want and it merges the profiles - you get to see the pilot's skills but you get the vehicles weapons, armour and hull trauma. I'm not exactly sure how to go about it yet, but it's in the pipeline.

**Comment by stoogoff** [comment]
Vehicles can be added to a character profile since version 2.0.0.
