### ISSUE TITLE
Genesys adversarys

### ISSUE THREAD

**Issue by SkyJedi** [stoogoff/sw-adversaries#17]
Any plans to mirror the app for Genesys?

**Comment by stoogoff** [comment]
Not currently, but maybe now that Realms of Terrinoth is out I might reconsider it. I'm not sure if it's worth trying to do an easily skinnable version of the app so it can be recreated for new settings or whether it would be better to have a generic Genesys version and have different settings split by the current tagging system.

**Comment by stoogoff** [comment]
Work has been done on this here: https://github.com/DPetrusma/genesys-adversaries
