### ISSUE TITLE
Not all menu/dropdowns visable

### ISSUE THREAD

**Issue by angrystatic** [stoogoff/sw-adversaries#19]
Not sure if this has already been addressed. 
On some occasions not all of the menu options are available in the GUI.
For example, right now I can't choose/search by book, adventure or species, only by name directly. I'd have to know the search term book:ragp...which I didn't know.

This is intermittent. I use Chrome in OS' ranging from Windows 10, to Windows 7, to Android, RPi Pixel, Linux Mint. Seems to work fine in IE 11
.

Is it possible that a browser extension is preventing this work working properly. UBlock Origin and Privacy Badger for example?

Or it could be that I have no idea what I'm talking about.

![2019-03-20 14_17_08-Star Wars_ Adversaries](https://user-images.githubusercontent.com/33765814/54712727-05803800-4b1b-11e9-85c0-3eb6e2fea99f.png)

![2019-03-20 14_23_42-Star Wars_ Adversaries - Internet Explorer](https://user-images.githubusercontent.com/33765814/54713136-e930cb00-4b1b-11e9-98b7-c8a349a66d4c.png)

**Comment by stoogoff** [comment]
Hi, thanks for contacting me. The GUI adjusts to fit the size of the display, hiding and showing different elements depending on how much space is available. You can see this if you're on a large screen and you resize the window. The side menu will hide itself as the window shrinks and eventually the characteristic layout will change.

This is working as intended but there's clearly some room for improvement around the search and menu options. I'll see what I can do to display the top menu for smaller screens.

**Comment by stoogoff** [comment]
Top navigation was improved on smaller screens in version 2.1.0.
