### ISSUE TITLE
Awesomeness

### ISSUE THREAD

**Issue by tex447** [stoogoff/sw-adversaries#2]
mr.stoogoff - I use the tool for every session of mine.  Just wanted to let you know the appreciation from my crew.

What do you recommend for keeping minion groups straight via the tabs at the bottom, for example if I have 3 minion groups and i lose track on the play board which group is which..is there a way to put a quick label on them such as "A", "B", and "C"?

**Comment by stoogoff** [comment]
Thanks! Glad you're finding it useful. At the moment with the tabs and minion groups I just try and remember or write something on a piece of paper, which is not ideal. I like your idea of labelling the tabs so I'll see about implementing that next week.

**Comment by stoogoff** [comment]
I've added tab renaming as well as a colour option.
