### ISSUE TITLE
Some problems to launch

### ISSUE THREAD

**Issue by FlowrianA** [stoogoff/sw-adversaries#24]
Hello there and thank you very much for all you're work  ! I'm French and I use your work for mastering my different FFG Role playing games ! 
However, for yesterday I encounter a little problem to launch some characters ( for example Maul, it's the only one that I remember sorry ).
This problem result of my computer or your application ? Can you make a check please ?  
Once again, many thanks to you !! And sorry for my English, I am more comfortable for speaking ^^
Thank You !

Florian

**Comment by stoogoff** [comment]
I made some changes yesterday which seem to have broken something. Thanks for letting me know, I'll get that fixed this morning.
