### ISSUE TITLE
Allow multiple version of the same NPC (feature request)

### ISSUE THREAD

**Issue by Tonic8** [stoogoff/sw-adversaries#27]
Hello

First many thanks for the fantastic work done.
It could be usefull to get on multipe version of the character, example Lando there is 3 versions :

-  Baron Administrator Lando Calrissian,
- Lando Calrissian (Allies and Adversaries), 
- Lando Calrissian (Dawn of Rebellion)

but they are scattered, maybe a link between them or using tab.

regards
Tonic8

**Comment by stoogoff** [comment]
I think this could be handled easily by tagging different versions with a tag so they can all be collected together. I'll add that to the task list.
