### ISSUE TITLE
Melee / Brawl weapon damage bug when creating/copying custom adversaries

### ISSUE THREAD

**Issue by AusRabbit** [stoogoff/sw-adversaries#34]
Love the product - you lot are champions.

I've just started making my own adversaries using sw-adversaries, often by copying one that is already present. I see the damage calculation against melee/brawl weapons is bugged. A simple truncheon (which might be +2 damage) is originally represented as 5 damage on the adversary. When I copy it and make changes such weapons display as 22 damage. This is clearly out of whack with the adversaries brawn and weapon details?

Wondering if that's something you might want to fix?

![image](https://user-images.githubusercontent.com/92836134/138016680-f584cd9c-1404-4935-8561-634362e0a59e.png)

**Comment by stoogoff** [comment]
If I add a truncheon to a character but don't change their Brawn value then it works correctly. If I change the Brawn value then it displays as you describe. So it's Javascript treating the Brawn value as a string not as a number.

Thanks for bringing that to my attention, I'll get that fixed.

**Comment by AusRabbit** [comment]
Amazing!

Thanks dude. I love this game and you make it possible.

Cheers, Rabs

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
