### ISSUE TITLE
ZIP Export From Adversaries Site Doesn't Contain All Assets

### ISSUE THREAD

**Issue by C1u1ch** [stoogoff/sw-adversaries#38]
Hi,

I'm not sure if I'm missing something.

I have followed the WIKI to the T and I'm missing quite a few assets which are on the site.

I can see the site has 1346 assets, and the ones I'm looking for as an example are the Battle Droid assets. When I import the data none of the Battle Droids are present.

Am I missing something?

**Comment by stoogoff** [comment]
Hi, the export only saves assets which you've created. If you want to export the battle droid you could copy it (it's in the menu to the left of the adversary type) and save it without any changes. Then when you export it will appear in the save files.

**Comment by C1u1ch** [comment]
Ok, so just to confirm - Following this guide here (https://github.com/StarWarsFoundryVTT/StarWarsFFG/wiki/Getting-started#importing-star-wars-adversaries-data) will not import all the assets from (https://swa.stoogoff.com/) into Foundry VTT?

It seems to import about 600 or so which is why I'm confused. I haven't made any custom assets or saved any. Why does it import some but not others?

**Comment by stoogoff** [comment]
Ah, we're taking at cross purposes. I thought you meant the import / export functionality built into SWA. The StarWarsFoundryVTT repo is nothing to do with me, you'll need to contact them about whatever the issue is.

**Comment by nlx3647** [comment]
In the zipfile you download, delete the csv folder. Then re-import. It will then import all 1341 adversaries.

In the next release of the alpha this will have been fixed in the importer.
