### ISSUE TITLE
Adjusting stats for dead minions

### ISSUE THREAD

**Issue by SkyJedi** [stoogoff/sw-adversaries#4]
As minions die there stats drop, I'm thinking theres a way to adjust that stats bases on the wound level entered into the derived stats area.  I'll poke around the code but I'm having a bugger of a time figuring out how to deploy it to aws

dude, your code is awesome

**Comment by stoogoff** [comment]
Thanks! You don't need to deploy to AWS unless you're hosting it yourself. To do this you'll need an AWS account and an S3 bucket. Once those are set up you'd need to create an aws.json file with access details for the S3 bucket and place that in the /build directory. The readme has specifics of the JSON file.

If you don't need to host then you can either build a dev or live version (`gulp live build` or `gulp dev build`) and use a browser to view the output.

If you've got some working code submit a pull request and I'll take a look.

**Comment by SkyJedi** [comment]
....see this is the kids stuff I'd know IF I knew how to code.  Thanks I'll poke around a little today.

**Comment by SkyJedi** [comment]
https://github.com/stoogoff/sw-adversaries/pull/5
