### ISSUE TITLE
Category Filtering Returning Blank Results

### ISSUE THREAD

**Issue by vkunnath** [stoogoff/sw-adversaries#40]
Hello,

Recently, it seems that if I want to filter by any of the categories from the dropdowns at the top of the page (Adventure, Species, Character, etc.), I get no results. For example, if I use "species:droid" to filter for all the droid characters in the database, I am given a blank list in the panel on the left.

I've checked this across Edge, Firefox, and Chrome after clearing the caches on each of them.

**Comment by stoogoff** [comment]
I've just taken a look and there's definitely something weird going on. Books still seem to work for some reason but the sources panel seems to be broken as well. I'll aim to get a fix in place this week.

Thanks for the heads up.

**Comment by stoogoff** [comment]
This is now fixed. The issue was tags were no longer being converted to lowercase before comparing them for the filter, which is why books (which use a lowercase code) still worked.
