### ISSUE TITLE
Custom adversaries?

### ISSUE THREAD

**Issue by TrailblazerDan** [stoogoff/sw-adversaries#9]
I love using this to keep track of adversaries!  Thanks for creating this amazing app.

How hard would it be to add a feature that lets GMs create their own adversaries and use your app to keep track of their stats?  I imagine the answer is "too hard to make it worthwhile," but I thought I'd ask...

**Comment by stoogoff** [comment]
This is a good idea which would be a big improvement on how the app works. Getting it done is going to be a bit time consuming though. I will get to it when I can.

**Comment by littlebigbucky** [comment]
Any future plans for this?

**Comment by stoogoff** [comment]
I do have a plan to add custom adversaries but I don't have much time to implement it at the moment.

**Comment by littlebigbucky** [comment]
Is there an easy way to import a json file?   People could bulk upload them
instead of using a custom UI. Put a custom tag in there and have them
hidden by default. Just thinking out loud.

**Comment by stoogoff** [comment]
Closed as part of release 2.2.0.
